<a href="https://colab.research.google.com/github/Abonty18/ML-lab/blob/main/190042118_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Task-1**

In [ ]:
import numpy as np
np.random.seed(0)
A = np.random.randint(17,size=(10))
print(A)

[12 15  0  3  3  7  9  4  6 12]


**Task-2**

In [ ]:
np.random.seed(0)
A = np.random.randint(80,size=(7,6))

print(A)
newA=A.reshape(3,14)
print(newA)

[[44 47 64 67 67  9]
 [21 36 70 12 58 65]
 [39 46 37 25 77 72]
 [ 9 20 69 79 47 64]
 [49 29 19 19 14 39]
 [32 65  9 57 32 31]
 [74 23 35 75 55 28]]
[[44 47 64 67 67  9 21 36 70 12 58 65 39 46]
 [37 25 77 72  9 20 69 79 47 64 49 29 19 19]
 [14 39 32 65  9 57 32 31 74 23 35 75 55 28]]


**Task-3**

In [ ]:
array = np.array([0,1,2,3,4,5,6,7,8,9])
odd=array[array % 2 == 1]
print(odd)


[1 3 5 7 9]


**Task-4**

In [ ]:
array[odd] = -1 
print(array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**Task-5**

In [ ]:
array = np.array([0,1,2,3,4,5,6,7,8,9])
arr = array.copy()
odd=array[array % 2 == 1]
print(odd)
array[odd] = -1 
print(array)
print(arr)



[1 3 5 7 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


**Task-6**

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print([key for key, val in enumerate(a) if val in set(b)])

[1, 3, 5, 7]


**Task-7**

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
indices = np.where((a>= 5) & (a<=10))
print(indices)
print(a[indices])

(array([1, 3, 4]),)
[ 6  9 10]


**Task-8**

In [ ]:
a = np.zeros((10))
print(a)
y = np.expand_dims(a, axis=(0, 1))
print(y)
b = np.ones((10))
print(b)
z = np.expand_dims(b, axis=(0, 1))
print(z)

np. concatenate ([y,z])


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]]


array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

**Task-9**

In [ ]:
x = np.random.rand(5, 4)
print("Original array: ")
print(x)

Original array: 
[[0.38344152 0.79172504 0.52889492 0.56804456]
 [0.92559664 0.07103606 0.0871293  0.0202184 ]
 [0.83261985 0.77815675 0.87001215 0.97861834]
 [0.79915856 0.46147936 0.78052918 0.11827443]
 [0.63992102 0.14335329 0.94466892 0.52184832]]
